# Generated by Django 5.0.4 on 2025-06-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerReportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_raised", models.DateTimeField()),
                ("reference", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
